const genres = [
  "JavaScript",
  "React Native",
  "Xamarin",
  "Flutter",
  "Dart",
  "Swift",
  "jQuery Mobile",
  "Dream Weaver",
  "Wordpress",
  "AdobeXD",
  "WebFlow",
  "Figma",
  "Canva",
  "Illustrator",
  "Photoshop",
  "CorelDraw",
  "Blender",
  "Ethical hacking",
  "PHP",
  "ReactJs",
  "Angular",
  "VueJs",
  "NodeJs",
  "ExpressJs",
  "MongoDB",
  "MySQL",
  "Laravel",
  "Django",
  "Unity",
  "Unreal Enging",
  "Solar2D",
  "Oracel",
  ".NET",
  "VanillaJs",
  "Cryptography",
  "TypeScript",
  "Python",
  "Data Science",
  "Machine Learning",
  "Cyber Security",
  "Digital Marketing",
  "Languages",
  "Project management",
  "Autocad",
  "Revit",
  "Excil",
  "MS Office",
  "Hackers",
  "Online Business",
  "Firebase",
];

export default genres;
